lib/notecastapp_web/router.ex
defmodule NotecastappWeb.Router do
  use NotecastappWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {NotecastappWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug NotecastappWeb.Auth
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", NotecastappWeb do
    pipe_through :browser

    get "/", PageController, :index
    resources "/users", UserController, only: [:index, :show, :new, :create]
    resources "/sessions", SessionController, only: [:new, :create, :delete]
  end

  scope "/manage", NotecastappWeb do
    pipe_through [:browser, :authenticate_user]

    resources "/folders", FolderController do
      resources "/documents", DocumentController
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", NotecastappWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: NotecastappWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end
end

lib/notecastapp/containers/document.ex
defmodule Notecastapp.Containers.Document do
  use Ecto.Schema
  import Ecto.Changeset

  schema "documents" do
    field :title, :string
    field :script, :string
    field :voice, :string
    field :filename, :string
    belongs_to :folder, Notecastapp.Containers.Folder

    timestamps()
  end

  @doc false
  def changeset(document, attrs) do
    document
    |> cast(attrs, [:title, :script, :voice, :filename])
    |> validate_required([:title, :script, :voice])
  end
end

lib/notecastapp_web/controllers/document_controller.ex
defmodule NotecastappWeb.DocumentController do
  use NotecastappWeb, :controller

  alias Notecastapp.Containers
  alias Notecastapp.Containers.Document
  alias Notecastapp.SpeechService
  alias Notecastapp.Parse

  def index(conn, _params) do
    documents = Containers.list_documents()
    render(conn, "index.html", documents: documents)
  end

  def new(conn, %{"folder_id" => folder_id}) do
    changeset = Containers.change_document(%Document{})
    folder = Containers.get_folder!(folder_id)
    documents = Containers.list_folder_documents(folder)
    render(conn, "new.html", changeset: changeset, folder: folder, documents: documents)
  end

  def create(conn, %{"document" => document_params, "folder_id" => folder_id}) do
    folder = Containers.get_folder!(folder_id)

    case Containers.create_document(folder_id, document_params) do
      {:ok, document} ->
        document
        |> Parse.parse(folder)
        |> SpeechService.synthesise(document)

        conn
        |> redirect(to: Routes.folder_document_path(conn, :show, folder, document.id))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset, folder: folder)
    end
  end

  def show(conn, %{"id" => id, "folder_id" => folder_id}) do
    document = Containers.get_document!(id)
    folder = Containers.get_folder!(folder_id)
    documents = Containers.list_folder_documents(folder)
    render(conn, "show.html", document: document, folder: folder, documents: documents)
  end

  def edit(conn, %{"id" => id, "folder_id" => folder_id}) do
    document = Containers.get_document!(id)
    changeset = Containers.change_document(document)
    folder = Containers.get_folder!(folder_id)
    documents = Containers.list_folder_documents(folder)

    render(conn, "edit.html",
      document: document,
      changeset: changeset,
      folder: folder,
      documents: documents
    )
  end

  def update(conn, %{"id" => id, "document" => document_params, "folder_id" => folder}) do
    document = Containers.get_document!(id)
    folder = Containers.get_folder!(folder)

    case Containers.update_document(document, document_params) do
      {:ok, document} ->
        document
        |> Parse.parse(folder)
        |> SpeechService.synthesise(document)

        conn
        |> redirect(to: Routes.folder_document_path(conn, :show, folder, document.id))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", document: document, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id, "folder_id" => folder_id}) do
    document = Containers.get_document!(id)
    folder = Containers.get_folder!(folder_id)

    {:ok, _document} = Containers.delete_document(document)

    documents = Containers.list_folder_documents(folder)

    if length(documents) > 0 do
      conn
      |> redirect(
        to:
          Routes.folder_document_path(conn, :show, folder_id, List.first(documents).id, documents)
      )
    end

    conn
    |> put_flash(:info, "Document deleted successfully.")
  end
end

lib/notecastapp_web/views/document_view.ex
defmodule NotecastappWeb.DocumentView do
  use NotecastappWeb, :view
  use Temple

  alias NotecastappWeb.Components.Sidebar
  alias NotecastappWeb.Components.Editor
  alias NotecastappWeb.Components.Display
  alias NotecastappWeb.Components.DocumentForm

  def options(folder) do
    %{"#{List.first(String.split(folder.language_one, ","))}": "#caf0cb", "#{List.first(String.split(folder.language_two, ","))}": "#f9d7a7"}
  end

  def language_one_hex() do
    "#D0E9F9"
  end

  def language_two_hex() do
    "#f9d7a7"
  end

end

lib/notecastapp_web/templates/document/edit.html.heex
<div id="editor" class="flex space-x-32 flex-row hidden pt-12">
    <div class="w-3/12">
      <Notecastapp.Misc.sidebar current={@document.id} plus={Routes.folder_document_path(@conn, :new, @folder.id)} folder={@folder.id} documents={@documents} title={@folder.title} />
    </div>
    <div class="w-9/12">

      <%= if @folder.language == true do %>
      <Notecastapp.Editor.editor render={render "form.html", Map.put(assigns, :action, Routes.folder_document_path(@conn, :update, @folder.id, @document.id))} delete={link "Delete", to: Routes.folder_document_path(@conn, :delete, @folder.id, @document.id), method: :delete, data: [confirm: "Are you sure?"], class: "w-full hover:bg-sky-200  rounded-full border border-neutral-800 text-neutral-800 px-2 py-0.5 font-medium"} cancel={Routes.folder_document_path(@conn, :show, @folder.id, @document)} items={%{"#{List.first(String.split(@folder.language_one, ","))}": "#caf0cb", "#{List.first(String.split(@folder.language_two, ","))}": "#f9d7a7"}} title={@document.title} />
      <% else %>
      <Notecastapp.Editor.editor render={render "form.html", Map.put(assigns, :action, Routes.folder_document_path(@conn, :update, @folder.id, @document.id))} delete={link "Delete", to: Routes.folder_document_path(@conn, :delete, @folder.id, @document.id), method: :delete, data: [confirm: "Are you sure?"], class: "w-full hover:bg-sky-200  rounded-full border border-neutral-800 text-neutral-800 px-2 py-0.5 font-medium"} cancel={Routes.folder_document_path(@conn, :show, @folder.id, @document)} items={%{"
🔈": "#D0E9F9"}} title={@document.title} />
      <% end %>
    </div>
    <div id="hidden-script" class="hidden"><%= raw(@document.script) %></div>
</div>

<style>
</style>

<script>
  document.addEventListener("DOMContentLoaded", function(event) { 
    window.editor.commands.setContent(document.getElementById("hidden-script").innerHTML)

    let editor = document.getElementById("editor");
    editor.classList.remove("hidden");
  });

  const addImage = () => {
    const url = window.prompt('URL')

    if (url) {
      window.editor.chain().focus().setImage({ src: url }).run()
    }
  }
</script> 

lib/notecastapp_web/templates/document/form.html.heex
<.form let={f} for={@changeset} action={@action}>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= label f, :title, class: "hidden" %>
  <%= text_input f, :title, id: "title", class: "hidden" %>
  <%= error_tag f, :title %>

  <%= label f, :script, class: "hidden" %>
  <%= textarea f, :script, id: "script", class: "hidden" %>
  <%= error_tag f, :script %>

  <%= label f, :voice, class: "hidden" %>
  <%= select f, :voice, [[key: "Libby", value: "en-GB-LibbyNeural"], [key: "Sonia", value: "en-GB-SoniaNeural"], [key: "Mia", value: "en-GB-MiaNeural"], [key: "Ryan", value: "en-GB-RyanNeural"], [key: "Dmitry", value: "ru-RU-DmitryNeural"]], class: "hidden" %>
  <%= error_tag f, :voice %>

  <div>
    <%= submit "Save document", id: "submit", class: "hover:bg-sky-200 hover:text-neutral-800 bg-neutral-800 text-white rounded-2xl py-3 px-8 font-medium" %>
  </div>
</.form>

lib/notecastapp_web/templates/document/index.html.heex
<h1>Listing Documents</h1>

<table>
  <thead>
    <tr>
      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for document <- @documents do %>
    <tr>

      <td>
        <span><%= link "Show", to: Routes.document_path(@conn, :show, document) %></span>
        <span><%= link "Edit", to: Routes.document_path(@conn, :edit, document) %></span>
        <span><%= link "Delete", to: Routes.document_path(@conn, :delete, document), method: :delete, data: [confirm: "Are you sure?"] %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "New Document", to: Routes.document_path(@conn, :new) %></span>

lib/notecastapp_web/templates/document/new.html.heex
<div id="editor" class="flex space-x-32 flex-row hidden pt-12">
    <div class="w-3/12">
      <Notecastapp.Misc.sidebar current={""} plus={Routes.folder_document_path(@conn, :new, @folder.id)}  folder={@folder.id} documents={@documents} title={@folder.title} />
    </div>
    <div  class="w-9/12">
      <%= if @folder.language == true do %>
        <Notecastapp.Editor.editor render={render "form.html", Map.put(assigns, :action, Routes.folder_document_path(@conn, :create, @folder.id))} delete={''}, class: {''}} cancel={Routes.folder_path(@conn, :show, @folder.id)} items={options(@folder)} title={''} />
      <%= else %>
      <Notecastapp.Editor.editor render={render "form.html", Map.put(assigns, :action, Routes.folder_document_path(@conn, :create, @folder.id))} delete={""}, class: {"w-full hover:bg-purple-200  rounded-full border border-neutral-800 text-neutral-800 px-2 py-0.5 font-medium"}} cancel={Routes.folder_path(@conn, :show, @folder.id)} items={%{"
🔈": "#D0E9F9"}} title={""} />
      <% end %>
    </div>
</div>

<style>
</style>

<script>
  document.addEventListener("DOMContentLoaded", function(event) { 
    let editor = document.getElementById("editor");
    editor.classList.remove("hidden");
  });


  const focusParent = () => {
    // alert("t")
     const html = editor.getHTML() 
     if (html === "<p>Enter some text ...</p>") {
      window.editor.commands.clearContent()
     }
  }

  document.addEventListener("keydown", event => {
    if (event.isComposing || event.keyCode === 9) {
      focusParent()
    }
  });

  const addImage = () => {
    const url = window.prompt('URL')

    if (url) {
      window.editor.chain().focus().setImage({ src: url }).run()
    }
  }
</script>   

lib/notecastapp_web/templates/document/show.html.heex
<div id="editor" class="flex space-x-32 flex-row  pt-12">
    <div class="w-3/12">
      <Notecastapp.Misc.sidebar current={@document.id} plus={Routes.folder_document_path(@conn, :new, @folder.id)} folder={@folder.id} documents={@documents} title={@folder.title} />
    </div>
    <div class="w-9/12">
        <Notecastapp.Editor.read_only_editor edit={"#{@document.id}/edit"} items={%{English: "#D0E9F9", Chinese: "#F4D8AD"}} title={@document.title} content={raw(@document.script)} />
        <%= content_tag :audio, src: "https://notefolder-bucket.s3.us-east-2.amazonaws.com/folders/#{@document.filename}", controls: true, class: "hidden", id: "audio" do %>
        <% end %>
    </div>
    <div id="hidden-script" class="hidden"><%= raw(@document.script) %></div>
</div>

<style>

  mark {
    cursor: pointer;
    /*background-color: transparent !important;*/
  }

  mark:hover {
    /*background-color: #D1EECE !important;*/
    filter: invert(1);
  }
</style>

<script>
    const play = (id, rate, button_id, speed) => {
        const audio = document.getElementById(id)
        audio.playbackRate = rate; 

        document.getElementById(button_id).innerHTML = `Pause (${speed})`

        audio.addEventListener('ended', () => end(id, button_id, speed))

        if (audio.paused) {
            audio.play()
            document.getElementById(button_id).innerHTML = `Pause (${speed})`
        } else {
            audio.pause()
            document.getElementById(button_id).innerHTML = `Listen (${speed})`
        }
    }

    const end = (id, button_id, speed) => {
        document.getElementById(button_id).innerHTML = `Listen (${speed})`
    }
</script> 

lib/notecastapp_web/templates/document/show2.html.heex
<div id="editor" class="flex space-x-32 flex-row  pt-12">
    <div class="w-3/12">
      <Notecastapp.Misc.sidebar current={@document.id} plus={Routes.folder_document_path(@conn, :new, @folder.id)} folder={@folder.id} documents={@documents} title={@folder.title} />
    </div>
    <div class="w-9/12">
        <Notecastapp.Editor.read_only_editor edit={"#{@document.id}/edit"} items={%{English: "#D0E9F9", Chinese: "#F4D8AD"}} title={@document.title} content={raw(@document.script)} />
        <%= content_tag :audio, src: "https://notefolder-bucket.s3.us-east-2.amazonaws.com/folders/#{@document.filename}", controls: true, class: "hidden", id: "audio" do %>
        <% end %>
    </div>
    <div id="hidden-script" class="hidden"><%= raw(@document.script) %></div>
</div>

<style>

  mark {
    cursor: pointer;
    /*background-color: transparent !important;*/
  }

  mark:hover {
    /*background-color: #D1EECE !important;*/
    filter: invert(1);
  }
</style>

<script>
    const play = (id, rate, button_id, speed) => {
        const audio = document.getElementById(id)
        audio.playbackRate = rate; 

        document.getElementById(button_id).innerHTML = `Pause (${speed})`

        audio.addEventListener('ended', () => end(id, button_id, speed))

        if (audio.paused) {
            audio.play()
            document.getElementById(button_id).innerHTML = `Pause (${speed})`
        } else {
            audio.pause()
            document.getElementById(button_id).innerHTML = `Listen (${speed})`
        }
    }

    const end = (id, button_id, speed) => {
        document.getElementById(button_id).innerHTML = `Listen (${speed})`
    }
</script> 

lib/notecastapp_web/templates/document/ttt.html.heex
<div id="editor" class="flex space-x-32 flex-row hidden pt-12">
    <div class="w-3/12">
      <Notecastapp.Misc.sidebar current={""} plus={Routes.folder_document_path(@conn, :new, @folder.id)}  folder={@folder.id} documents={@documents} title={@folder.title} />
    </div>
    <div  class="w-9/12">
      <%= if @folder.language == true do %>
        <Notecastapp.Editor.editor render={render "form.html", Map.put(assigns, :action, Routes.folder_document_path(@conn, :create, @folder.id))} delete={''}, class: {''}} cancel={Routes.folder_path(@conn, :show, @folder.id)} items={options(@folder)} title={''} />
      <%= else %>
      <Notecastapp.Editor.editor render={render "form.html", Map.put(assigns, :action, Routes.folder_document_path(@conn, :create, @folder.id))} delete={""}, class: {"w-full hover:bg-purple-200  rounded-full border border-neutral-800 text-neutral-800 px-2 py-0.5 font-medium"}} cancel={Routes.folder_path(@conn, :show, @folder.id)} items={%{"
🔈": "#D0E9F9"}} title={""} />
      <% end %>
    </div>
</div>

<style>
</style>

<script>
  document.addEventListener("DOMContentLoaded", function(event) { 
    let editor = document.getElementById("editor");
    editor.classList.remove("hidden");
  });


  const focusParent = () => {
    // alert("t")
     const html = editor.getHTML() 
     if (html === "<p>Enter some text ...</p>") {
      window.editor.commands.clearContent()
     }
  }

  document.addEventListener("keydown", event => {
    if (event.isComposing || event.keyCode === 9) {
      focusParent()
    }
  });

  const addImage = () => {
    const url = window.prompt('URL')

    if (url) {
      window.editor.chain().focus().setImage({ src: url }).run()
    }
  }
</script>   